### ISSUE TITLE
Configure memory caches on startup

### ISSUE THREAD

**Issue by sapir** [esp-rs/xtensa-lx6-rt#11]
ESP-IDF's cpu_start.c calls `Cache_Flush_rom(0)` and `Cache_Read_Enable_rom(0)` (via `Cache_Flush(0)` and `Cache_Read_Enable(0)`, respectively) on startup. This may be necessary in some cases.

**Comment by arjanmels** [comment]
This is done in the bootloader, I am not 100% certain if done in the ROM bootloader, but it is done in the 2nd stage bootloader.
I do have a PR on the esp32-hal to be able to use the 2nd stage bootloader: https://github.com/esp-rs/esp32-hal/pull/16
(This is also needed to be able to run from Flash etc.)

Imho, in any case this should be done in the esp32-hal crate as it is esp32 specific, not xtensa-lx6 generic.
