### ISSUE TITLE
Implement the exception vectors

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/xtensa-lx6-rt#4]
#3 added a statically built archive of the execption vectors (taken from an IDF project) For most of the symbols, we simply need to install the vectors into the right place in memory, the WindowOverflow and WindowUnderflow vectors. 

Some for some vectors, we want to be able to specify user handlers for these exceptions to troubleshoot system level faults. In which case, by using the prebuilt vectors from IDF we also have to use the idf mechanism for doing so, see [xtensa_intr](https://github.com/espressif/esp-idf/blob/master/components/freertos/xtensa_intr.c).

**Comment by igrr** [comment]
@MabezDev Do you have any pointers, what could an implementation of exception vectors in Rust look like? I assume we still need a bit of assembly to save the registers and set up the register windows, before Rust code can be called.

**Comment by MabezDev** [comment]
They way its [implemented in cortex-m-rt](https://github.com/rust-embedded/cortex-m-rt/blob/093dc07908806cc430bd3baaa4812de2ee1e8678/src/lib.rs#L763) is essentially a block of function pointers.

I'm still trying to get my head around the windowed abi but I think your right. I guess we need a default implementation in assembly to save reg state before calling into the rust functions?

Seems like [xtensa_vectors.S](https://github.com/espressif/esp-idf/blob/600d542f53ab6540d277fca4716824d168244c8c/components/freertos/xtensa_vectors.S#L1618) would provide all of that for us, though it looks like there are a few idf specific `#define`'s sprinkled in.

**Comment by igrr** [comment]
> Seems like xtensa_vectors.S would provide all of that for us, though it looks like there are a few idf specific #define's sprinkled in.

Yes, about right. Another place which you can look at is Zephyr RTOS project arch/xtensa directory: https://github.com/zephyrproject-rtos/zephyr/tree/master/arch/xtensa/core. For example, their Level 1 handler is implemented in C (with a bit of inline asm), which might make it easier to parse: https://github.com/zephyrproject-rtos/zephyr/blob/a290d30c9ace9c6e4d2c8f9c7d8fd5d284a10d2c/arch/xtensa/core/xtensa-asm2.c#L167. One note is that Zephyr uses a slightly different mechanism for window spilling, so the exception handling code from there can not always be mixed and matched with IDF exception handling code.

**Comment by arjanmels** [comment]
Also closed by #12
